language: php
php:
  - 7.2

install:
  - composer require php-coveralls/php-coveralls

before_script:
  - composer self-update
  - composer install
  
script: 
  - mkdir -p build/logs
  - php vendor/bin/phpunit -v -c phpunit.xml --coverage-text --coverage-clover=./build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v