language: php
php:
  - 7.2

install:
  - composer require satooshi/php-coveralls:dev-master

before_script:
  - composer self-update
  - composer install
  - composer require php-coveralls/php-coveralls
  
script: 
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -v -c phpunit.xml --coverage-text --coverage-clover=./build/logs/clover.xml

after_script: 
  - php vendor/bin/coveralls -v 

