language: php
php:
  - 7.2

install:
  - composer require php-coveralls/php-coveralls

before_script:
  - composer self-update
  - composer install
  
script: 
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -v -c phpunit.xml --coverage-text --coverage-clover=./build/logs/clover.xml

after_script: 
  - php ./vendor/bin/coveralls -v 

