language: php
php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install
  
script: ./vendor/bin/phpunit -v -c test/PHPUnitConfiguration.xml --coverage-text  --coverage-clover=coverage.clover
